# frozen_string_literal: true

source "https://rubygems.org"

gem "rake"
gem "sinatra"
gem "puma"
gem "activesupport"
gem "activerecord"
#gem "mysql2"
#gem "pg"
gem "sqlite3"
gem "redis"
gem "redis-namespace"
